"""initial

Revision ID: 1326884a362c
Revises: 
Create Date: 2026-04-06 17:59:43.196031
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1326884a362c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=5000), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_configs_key'), 'experiment_configs', ['key'], unique=True)
    op.create_table('experiment_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_sessions_event'), 'experiment_sessions', ['event'], unique=False)
    op.create_index(op.f('ix_experiment_sessions_participant_id'), 'experiment_sessions', ['participant_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.String(length=10), nullable=False),
    sa.Column('prolific_id_encrypted', sa.String(length=256), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('study_id', sa.String(length=100), nullable=True),
    sa.Column('task_type', sa.Enum('emotionTask', 'functionTask', name='tasktype'), nullable=False),
    sa.Column('partnership', sa.Enum('HHC', 'HMC', name='partnership'), nullable=False),
    sa.Column('partner_label', sa.Enum('chatbot', 'human', name='partnerlabel'), nullable=False),
    sa.Column('current_step', sa.Enum('consent', 'welcome', 'priming', 'instructions_r1', 'chat_r1', 'instructions_r2', 'chat_r2', 'survey_prompt', 'survey_a', 'survey_b', 'demographics', 'payment', name='step'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('is_timeout', sa.Boolean(), nullable=False),
    sa.Column('hhc_fallback', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('priming_text', sa.String(length=2000), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prolific_id_encrypted')
    )
    op.create_index(op.f('ix_participants_display_id'), 'participants', ['display_id'], unique=True)
    op.create_table('chat_rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('room_type', sa.Enum('HHC', 'HMC', name='roomtype'), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=50), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_participant_id'), 'chat_rooms', ['participant_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_room_id'), 'chat_rooms', ['room_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('sen_a_1', sa.Integer(), nullable=True),
    sa.Column('sen_a_2', sa.Integer(), nullable=True),
    sa.Column('sen_a_3', sa.Integer(), nullable=True),
    sa.Column('sen_a_4', sa.Integer(), nullable=True),
    sa.Column('fee_h_1', sa.Integer(), nullable=True),
    sa.Column('fee_h_2', sa.Integer(), nullable=True),
    sa.Column('fee_h_3', sa.Integer(), nullable=True),
    sa.Column('fee_h_4', sa.Integer(), nullable=True),
    sa.Column('ce_1', sa.Integer(), nullable=True),
    sa.Column('ce_2', sa.Integer(), nullable=True),
    sa.Column('ce_3', sa.Integer(), nullable=True),
    sa.Column('ce_4', sa.Integer(), nullable=True),
    sa.Column('manip_check', sa.Integer(), nullable=True),
    sa.Column('ai_usage', sa.Integer(), nullable=True),
    sa.Column('ail_1', sa.Integer(), nullable=True),
    sa.Column('ail_2', sa.Integer(), nullable=True),
    sa.Column('ail_3', sa.Integer(), nullable=True),
    sa.Column('ail_4', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('partisanship', sa.String(length=50), nullable=True),
    sa.Column('rlg_1', sa.Integer(), nullable=True),
    sa.Column('rlg_2', sa.Integer(), nullable=True),
    sa.Column('rlg_3', sa.Integer(), nullable=True),
    sa.Column('rlg_4', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_participant_id'), 'survey_responses', ['participant_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_room_id', sa.Uuid(), nullable=False),
    sa.Column('sender_role', sa.Enum('user', 'partner', name='senderrole'), nullable=False),
    sa.Column('text', sa.String(length=5000), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_room_id'), 'chat_messages', ['chat_room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_chat_room_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_survey_responses_participant_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_chat_rooms_room_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_participant_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_participants_display_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_experiment_sessions_participant_id'), table_name='experiment_sessions')
    op.drop_index(op.f('ix_experiment_sessions_event'), table_name='experiment_sessions')
    op.drop_table('experiment_sessions')
    op.drop_index(op.f('ix_experiment_configs_key'), table_name='experiment_configs')
    op.drop_table('experiment_configs')
    # ### end Alembic commands ###
