"""add_resume_token_and_step_columns

Revision ID: b70ace7d4d4f
Revises: 634d4b432ce1
Create Date: 2026-05-14 18:32:17.498311
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70ace7d4d4f'
down_revision: Union[str, None] = '634d4b432ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_sessions', sa.Column('step', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_experiment_sessions_step'), 'experiment_sessions', ['step'], unique=False)
    op.add_column('participants', sa.Column('resume_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_participants_resume_token'), 'participants', ['resume_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_resume_token'), table_name='participants')
    op.drop_column('participants', 'resume_token')
    op.drop_index(op.f('ix_experiment_sessions_step'), table_name='experiment_sessions')
    op.drop_column('experiment_sessions', 'step')
    # ### end Alembic commands ###
